/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    colors: {
      system: {
        red: "#dc3545",
        redHover: "#bb2d3b",
        bostonUniversityRed: "#cc0000",
        ceruleanBlue: "#3b4cca",
        goldenYellow: "#ffde00",
        goldenFoil: "#b3a125",
        borderGray: "#cbcbcb",
        green: "#198754",
        greenHover: "#157347",
        blue: "#0d6efd",
        blueHover: "#0b5ed7",
        grayBorder: "#ced4da",
      },
      themed: {
        cultured: "#f8f8f8",
        pokeballBlack: "#010101",
        pokeballWhite: "#fff",
        pokeballRed: "#eb2127",
        containerGray: "rgba(0, 0, 0, 0.03)",
        containerGrayBorder: "rgba(0, 0, 0, 0.175)",
      },
      types: {
        normal: "#a8a77a",
        fire: "#ee8130",
        water: "#6390f0",
        electric: "#f7d02c",
        grass: "#7ac74c",
        ice: "#96d9d6",
        fighting: "#c22e28",
        poison: "#a33ea1",
        ground: "#e2bf65",
        flying: "#a98ff3",
        psychic: "#f95587",
        bug: "#a6b91a",
        rock: "#b6a136",
        ghost: "#735797",
        dragon: "#6f35fc",
        dark: "#705746",
        steel: "#b7b7ce",
        fairy: "#d685ad",
      },
      bg: {
        gray: "#f8f9fa",
        blue: {
          default: "#3890d8",
          light: "#80c0d8",
          hover: "#78d0e8",
          hoverLight: "#a8e8f8",
        },
      },
      disabled: "#6c757d",
    },
  },
  plugins: [],
};
